sonar.organization=thehmars
sonar.projectKey=theHmars_engine
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.venv/**,**/venv/**,**/tmp/**,**/tests/**,**/mock-data/**,**/data/**
sonar.host.url=https://sonarcloud.io
