#!/usr/bin/env python3
import os
import sys
import json

# Setup paths to import LLM client
scripts_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
engine_dir = os.path.dirname(scripts_dir)
sys.path.append(engine_dir)

try:
    from utils.llm_client import call_llm
    from utils.common import get_state_dir
except ImportError as e:
    print(f"[-] Could not import call_llm or get_state_dir: {e}")
    sys.exit(1)

def curate_articles():
    # Paths to the JSON files generated by prepare_candidates.py
    tmp_dir = os.path.join(get_state_dir(), "tmp")
    list_path = os.path.join(tmp_dir, "list.json")
    metadata_path = os.path.join(tmp_dir, "metadata.json")
    
    if not os.path.exists(list_path) or not os.path.exists(metadata_path):
        print("[-] Curator: list.json or metadata.json not found. Exiting.")
        sys.exit(0)
        
    with open(list_path, 'r', encoding='utf-8') as f:
        candidates = json.load(f)
        
    with open(metadata_path, 'r', encoding='utf-8') as f:
        metadata = json.load(f)
        
    if not candidates:
        print("[-] Curator: No candidates to curate. Exiting.")
        sys.exit(0)
        
    quota = metadata.get("quota", 10)
    
    # Short-circuit logic: If we don't have more candidates than the quota, don't bother the LLM.
    if len(candidates) <= quota:
        print(f"[*] Candidates ({len(candidates)}) <= Quota ({quota}). Bypassing LLM AI Curator and selecting all.")
        winning_ids = [c["id"] for c in candidates]
        output_path = os.path.join(tmp_dir, "curated_ids.json")
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(winning_ids, f)
        return winning_ids
        
    print(f"[*] AI Curator woke up. Analyzing {len(candidates)} candidates to select the top {quota}...")

    prompt_path = os.path.join(os.path.dirname(__file__), "social_curator.txt")
    if not os.path.exists(prompt_path):
        print(f"[-] Curator Prompt not found at {prompt_path}. Exiting.")
        sys.exit(1)
        
    with open(prompt_path, 'r', encoding='utf-8') as f:
        system_prompt = f.read()
        
    # Format the payload for the LLM
    # We strip out 'featured_image_url' so the LLM isn't distracted by raw URLs
    user_payload_data = []
    for c in candidates:
        payload_item = {
            "id": c["id"],
            "title": c["title"],
            "summary": c["summary"],
            "scope": c.get("scope", "N/A"),
            "featured_image": c.get("featured_image", "")
        }
        user_payload_data.append(payload_item)

    effective_quota = min(quota, len(candidates))
    user_payload = f"You must select EXACTLY {effective_quota} articles from the list below.\n\n"
    user_payload += "### CANDIDATES\n"
    user_payload += json.dumps(user_payload_data, indent=2)
    
    try:
        # call_llm already returns a parsed dict — no .strip() or json.loads() needed
        decision = call_llm(system_prompt, user_payload)
        
        print(f"[+] AI Curator Rationale: {decision.get('rationale', 'No rationale provided')}")
        
        winning_ids = decision.get("winning_ids", [])
        if not isinstance(winning_ids, list):
            print(f"[!] Curator returned unexpected type for winning_ids: {type(winning_ids)}. Falling back.")
            winning_ids = []
        
        # Ensure we don't accidentally exceed effective quota or crash the publisher
        final_selection = winning_ids[:effective_quota]
        
        print(f"[+] Final Winning IDs: {final_selection}")
        
        # Export the winning IDs for publisher.py
        output_path = os.path.join(tmp_dir, "curated_ids.json")
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(final_selection, f)
            
        return final_selection
        
    except Exception as e:
        print(f"[!] Curator LLM Error: {e}")
        # Fallback Protocol: Select the first N items so the pipeline doesn't crash
        print(f"[!] Fallback: Selecting the first {effective_quota} items automatically.")
        fallback = [c["id"] for c in candidates[:effective_quota]]
        output_path = os.path.join(tmp_dir, "curated_ids.json")
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(fallback, f)
        return fallback

if __name__ == "__main__":
    curate_articles()
